eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    
services:
    payment-service:
      urls:
        url: http://PaymentService/paymentControl/api/v1/doPayment
    order-service:
      urls:
        url: http://PaymentService/paymentControl/api/v1/doPayment

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true
