eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    
services:
 urls:
  paymentUrl:
   http://PaymentService/paymentControl/api/v1/doPayment
  orderUrl:
   http://OrderService/order/api/v1/save
  MyUrl:
   thisiscomingfromGitUrl-V2

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    circuitbreakers:
      enabled: true

